package ch.szclsb.kerinci.internal.vulkan;

import ch.szclsb.kerinci.internal.Flag;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum KrcFormatFeatureFlag implements Flag {
    SAMPLED_IMAGE_BIT(0x00000001),
    STORAGE_IMAGE_BIT(0x00000002),
    STORAGE_IMAGE_ATOMIC_BIT(0x00000004),
    UNIFORM_TEXEL_BUFFER_BIT(0x00000008),
    STORAGE_TEXEL_BUFFER_BIT(0x00000010),
    STORAGE_TEXEL_BUFFER_ATOMIC_BIT(0x00000020),
    VERTEX_BUFFER_BIT(0x00000040),
    COLOR_ATTACHMENT_BIT(0x00000080),
    COLOR_ATTACHMENT_BLEND_BIT(0x00000100),
    DEPTH_STENCIL_ATTACHMENT_BIT(0x00000200),
    BLIT_SRC_BIT(0x00000400),
    BLIT_DST_BIT(0x00000800),
    SAMPLED_IMAGE_FILTER_LINEAR_BIT(0x00001000),
    TRANSFER_SRC_BIT(0x00004000),
    TRANSFER_DST_BIT(0x00008000),
    MIDPOINT_CHROMA_SAMPLES_BIT(0x00020000),
    SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT(0x00040000),
    SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT(0x00080000),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT(0x00100000),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT(0x00200000),
    DISJOINT_BIT(0x00400000),
    COSITED_CHROMA_SAMPLES_BIT(0x00800000),
    SAMPLED_IMAGE_FILTER_MINMAX_BIT(0x00010000),
    VIDEO_DECODE_OUTPUT_BIT_KHR(0x02000000),
    VIDEO_DECODE_DPB_BIT_KHR(0x04000000),
    ACCELERATION_STRUCTURE_VERTEX_BUFFER_BIT_KHR(0x20000000),
    SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT(0x00002000),
    FRAGMENT_DENSITY_MAP_BIT_EXT(0x01000000),
    FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR(0x40000000),
    SAMPLED_IMAGE_FILTER_CUBIC_BIT_IMG(SAMPLED_IMAGE_FILTER_CUBIC_BIT_EXT.value),
    TRANSFER_SRC_BIT_KHR(TRANSFER_SRC_BIT.value),
    TRANSFER_DST_BIT_KHR(TRANSFER_DST_BIT.value),
    SAMPLED_IMAGE_FILTER_MINMAX_BIT_EXT(SAMPLED_IMAGE_FILTER_MINMAX_BIT.value),
    MIDPOINT_CHROMA_SAMPLES_BIT_KHR(MIDPOINT_CHROMA_SAMPLES_BIT.value),
    SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT_KHR(SAMPLED_IMAGE_YCBCR_CONVERSION_LINEAR_FILTER_BIT.value),
    SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT_KHR(SAMPLED_IMAGE_YCBCR_CONVERSION_SEPARATE_RECONSTRUCTION_FILTER_BIT.value),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT_KHR(SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_BIT.value),
    SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT_KHR(SAMPLED_IMAGE_YCBCR_CONVERSION_CHROMA_RECONSTRUCTION_EXPLICIT_FORCEABLE_BIT.value),
    DISJOINT_BIT_KHR(DISJOINT_BIT.value),
    COSITED_CHROMA_SAMPLES_BIT_KHR(COSITED_CHROMA_SAMPLES_BIT.value),
    FLAG_BITS_MAX_ENUM(0x7FFFFFFF);

    private final int value;
}
